# Generated by Django 2.1.7 on 2019-03-18 22:57
from django.db import migrations
from django.core.exceptions import FieldDoesNotExist

from wells import data_migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0066_auto_20190318_2257'),
    ]

    operations = [
        migrations.RunPython(
            data_migrations.update_geom_fields, reverse_code=data_migrations.reverse_update_geom_fields),
        migrations.RemoveField(
            model_name='activitysubmission',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='activitysubmission',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='well',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='well',
            name='longitude',
        ),
    ]
